<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2015-12-14T17:06:47+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.latest_version
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'site' => 'yakamoz',
    'version_installed' => '5.7.5.3',
    'misc' => array(
        'access_entity_updated' => 1449589594,
        'mobile_theme_id' => 0,
        'latest_version' => '5.7.5.3',
    ),
);
